server:
  port: 8888
spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: C:\\Users\\20222656\\Documents\\testas2
          clone-on-start: true
          default-label: master
management:
  security:
    enabled: false